name: Deploy website to Manitu on push
on: 
  push:
    tags: 
      - '*' 
    branches: 
      - main
    
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v2
      with:
        node-version: '22'
      
    - name: Build Project
      run: |
        cd project-amsterdam
        npm install
        npm run build
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ngcobalt440.manitu.net
        username: ${{ secrets.MANITU_FTP_USER }}
        password: ${{ secrets.MANITU_FTP_SECRET }}
        local-dir: ./dist/
        server-dir: web/schergen.org/
